### ISSUE TITLE
∞ loop fun :-)

### ISSUE THREAD

**Issue by wmertens** [autotelicum/Smooth-CoffeeScript#14] opened 2012-01-25 09:29 UTC
In exercise 3 of Interactive Smooth Coffeescript the student will probably write something like

``` coffeescript
    i=0
    while i<10
      [sudden hang]
```

The reason of course is that the student doesn't get a chance to add i++ before the automatic evaluation hangs the page.

I was thinking that this could be solved with either webworkers which are only allowed to run for a certain amount of time, or else by amending all while loops with hidden max-iteration code.

**Comment by autotelicum** [comment] 2012-01-25 10:01
Thanks for calling this to my attention. I knew that infinite loops would break things, but didn't realize that it would be that easy to trigger the problem.

Using a web worker (and throttling) was on my todo list once, I dropped it because of IE9. But IE9 does not really work and fixing this is clearly more important. I will create some experiments and see what the consequences for the output functions will be.

**Comment by autotelicum** [comment] 2012-01-25 20:56
Progress report: Hmm... a workaround is to disable `Auto evaluate` up at the top of the document. Then press `shift/enter` after every edit. That will reduce the chance of an accidental hang.

But it is not a very good workaround, because if you evaluate something that contains an infinite loop or mutual recursion the whole thing will still hang. I have just had two kernel panics on OS X when writing `loop then<Enter>` in the CoffeeScript REPL. The REPL does not respond to Ctrl-C and when closing the Terminal the panic _might_ happen (2 out of 3 tries for me on 10.6.8), the active process was `node`.

I played around with WebWorkers but they are difficult in this situation because the DOM is not thread safe, all output would have to be routed through posting events, then there is sequencing and the global environment is not available. Not impossible but definitely some work seems to be involved, WebWorkers are also not available in the Android 4.0 browser.

So... I am currently experimenting with instrumenting the code in its nodes/AST form, essentially what a profiler would do, then breaking the code by `throw`ing an exception when a threshold is exceeded. Possibly that will not work when the code under execution contains a `try`/`catch`, so it might be a blind alley, and the generated JS no longer resembles the original code ie. `show functionname` does not work.

Interesting problem, it is ∞ fun. Maybe there is no general solution; a hack might be to `grep` the code for a few patterns that are likely to occur during editing.

**Comment by wmertens** [comment] 2012-01-25 21:22
Wow nice avenues you explored there! Amazing that you got OS X to crash that way, a little depressing actually.

I like the instrumenting approach, it will greatly reduce the chance of a hang. Possibly `show functionname` could remove the instrumenting?

I forgot the name, but there's this theorem that states that it's impossible for a program to know if it will end in a finite amount of time. So your hack seems like the best approach - add counters to while loops and recursion or simply switch to non-auto mode when you detect either (and warn the user).

**Comment by autotelicum** [comment] 2012-01-26 00:33
# SCOOPING THE LOOP SNOOPER

## A proof that the Halting Problem is undecidable

**Geoffrey K. Pullum**
 (_School of Philosophy, Psychology and Language Sciences, University of Edinburgh_)

---

  _No general procedure for bug checks succeeds._
   Now, I won’t just assert that, I’ll show where it leads: 
   I will prove that although you might work till you drop, 
   you cannot tell if computation will stop.

  For imagine we have a procedure called _P_ 
   that for specified input permits you to see
   whether specified source code, with all of its faults,
   defines a routine that eventually halts.

  You feed in your program, with suitable data, 
   and _P_ gets to work, and a little while later 
   (in finite compute time) correctly infers
   whether infinite looping behavior occurs.

  If there will be no looping, then _P_ prints out ‘Good.’
   That means work on this input will halt, as it should.
   But if it detects an unstoppable loop,
   then _P_ reports ‘Bad!’ --- which means you’re in the soup.

  Well, the truth is that _P_ cannot possibly be, 
   because if you wrote it and gave it to me, 
   I could use it to set up a logical bind 
   that would shatter your reason and scramble your mind.

  Here’s the trick that I’ll use -- and it’s simple to do. 
   I’ll define a procedure, which I will call _Q_,
   that will use P's predictions of halting success 
   to stir up a terrible logical mess.

  For a specified program, say _A_, one supplies,
   the first step of this program called _Q_ I devise
   is to find out from _P_ what’s the right thing to say
   of the looping behavior of _A_ run on _A_.

  If P's answer is ‘Bad!’, _Q_ will suddenly stop. 
   But otherwise, _Q_ will go back to the top, 
   and start off again, looping endlessly back, 
   till the universe dies and turns frozen and black.

  And this program called _Q_ wouldn’t stay on the shelf; 
   I would ask it to forecast its run on _itself_.
   When it reads its own source code, just what will it do? 
   What’s the looping behavior of _Q_ run on _Q_?

  If _P_ warns of infinite loops, _Q_ will quit; 
   yet _P_ is supposed to speak truly of it! 
   And if Q’s going to quit, then _P_ should say ‘Good.’
   Which makes _Q_ start to loop! (_P_ denied that it would.)

  No matter how _P_ might perform, _Q_ will scoop it: 
   _Q_ uses P’s output to make _P_ look stupid.
   Whatever _P_ says, it cannot predict _Q_: 
   _P_ is right when it’s wrong, and is false when it’s true!

  I’ve created a paradox, neat as can be ---
   and simply by using your putative _P_. 
   When you posited _P_ you stepped into a snare; 
   Your assumption has led you right into my lair.

  So where can this argument possibly go? 
   I don’t have to tell you; I’m sure you must know. 
   A _reductio_ : There cannot possibly be 
   a procedure that acts like the mythical _P_.

  You can never find general mechanical means
   for predicting the acts of computing machines; 
   it’s something that cannot be done. So we users 
   must find our own bugs. Our computers are losers!

---

Copyright © 2008 by Geoffrey K. Pullum.
Permission is granted to reproduce or distribute this work for non-commercial, educational purposes relating to teaching computer science, mathematics, or logic.

[Poem source](http://www.lel.ed.ac.uk/~gpullum/loopsnoop.html)

**Comment by wmertens** [comment] 2012-01-26 23:09
Haha great find :)

**Comment by autotelicum** [comment] 2012-01-27 20:46
_"Here's another nice mess you've gotten me into."_

No quick fix. The patches I have tried all have unintended consequences. I also tested a number of online CoffeeScript/JavaScript services to see if anyone else had solved the problem, but they all spun out of control. The problem is worse _here_ because of CoffeeScript's succinct syntax and because I chose to make 'live' coding the default. I like the minimal book design and the instant response on syntax and results, so I don't want to give up on it.

The problem, that infinite loops have a deadly effect on some browsers, is mentioned in 'Getting started' (What happened to time outs? Why does `eval` not have a `max-time` argument?) and it is clearly marked in the chicken-and-egg example. Although that is not much consolation for a reader that unwittingly steps into the trap in Exercise 2 or 3. I want to add that I often finish new examples by editing them in the live document and pasting them back into the markdown ... and I have not encountered the issue yet.

Instead of trying to patch it, what I'll do is: bring profile instrumentation into the next version of the little piece of machinery, [Grimoire](http://autotelicum.github.com/Smooth-CoffeeScript/interactive/grimoire.html), that runs the code inside the documents. I was already preparing to make it an independent project with some new ideas, cleaning up, adding a few features, an additional programming language, and removing the `plan9` dependency. In other words this is going to take an unspecified amount of time. At least it will be interesting to design and implement as a solution - and there isn't much point in doing any of this - for me - unless the journey is fun. It now has its own project over [there](https://github.com/autotelicum/grimoire/).

**Comment by wmertens** [comment] 2012-01-28 04:03
Fair enough… I suppose the best workaround is to add a warning to Exercise 3 about first writing the "  i++" line and then the while line above it?

I did encounter the problem quite easily, maybe I'm a slow writer or Chrome on OS X is really twitchy :-)

Lovely intro you wrote for Grimoire BTW, good stuff!

**Comment by autotelicum** [comment] 2012-01-28 09:38
I don't think it is typing speed or your browser. My guess is that it is because `for`, `each`, `map`, … are less likely to trigger the problem than `while` and `loop`. So I created an [update](https://github.com/autotelicum/Smooth-CoffeeScript/commit/1dc4365525c1b5fef43f69e8303cea8a6b1e276b) based on that assumption with a modification of exercises 2+3 and a note in-between on the issue.

You may have to clear your cache and restart your browser to see the change. It shouldn't be like that, but I have no control over the web server and apparently browsers ignore changes to the appcache file if it is not served with the right MIME type. The appcache is for offline browsing, that is a neat feature in HTML5. With it I can load the book in Mobile Safari, go somewhere without internet, write an ∞ loop, restart Mobile Safari and reload the book from the cache. Oh joy!

**Comment by autotelicum** [comment] 2012-01-29 13:44
Moved issue to https://github.com/autotelicum/grimoire/issues/1

**Closed as completed by autotelicum** 2012-01-29 13:44 UTC
